### ISSUE TITLE
Performance improvement 

### ISSUE THREAD

**Issue by marthinus-engelbrecht** [dougludlow/plugin-sass#59]
Hi, 

By keeping track of the actual imports done by the `sass.importer` we could just do a `sass.writefile` to memory and then do a `sass.readfile` the next time that same dependency is being imported instead of doing another http request. I hacked the code and it this actual works and the code is pretty simple. Don't have time at the moment to do a pull request though.

**Comment by screendriver** [comment]
Thank you for your feedback. I try to play around with that in the next time. Any pull request for that would be welcome as well 😉

**Comment by dougludlow** [comment]
@marthinus-engelbrecht this works for the builder but not the web, right?

I'm closing this for now due to inactivity, feel free to reopen to renew the discussion.
