### ISSUE TITLE
Base plugin-sass on css-plugin-base?

### ISSUE THREAD

**Issue by ineentho** [dougludlow/plugin-sass#72]
Have you thought about basing this plugin on plugin-css as the less plugin does? I think we should learn some things from them.

One problem I'm having with this plugin is that incremental builds get really slow because it seems like the cache doesn't work, which I believe is solved correctly by the less plugin.

If I were to prepare a pull request that implements it, would you consider to merge it?

**Comment by screendriver** [comment]
Thank you for the suggestion. Any pull request is welcome 😎 👍

**Comment by dougludlow** [comment]
@ineentho feel free to submit a or any time, if your still interested. I'll close this issue for now. 

From what I understand, the main reason it's pretty slow is because we rely on sass.js which is very slow. That's the limitation.
