### ISSUE TITLE
SystemJS 0.20 compatibility

### ISSUE THREAD

**Issue by guybedford** [dougludlow/plugin-sass#78]
From https://github.com/jspm/jspm-cli/issues/2219

If running this against SystemJS with `System.config({ warnings: true })` it will warn that the line at https://github.com/mobilexag/plugin-sass/blob/master/src/index.js#L9 is invalid.

Updating this to `System.import('./sass-inject', __moduleName );` should resolve the issue, although there may be other compatibility fixes needed.

Just let me know if I can help further on the upgrade path.

**Comment by screendriver** [comment]
This plugin is abandoned. Unfortunately we switched the technology and don't have the time and bugdet to maintain this plugin anymore.

I updated the README. However everyone can maintain this plugin furthermore (we would transfer the whole project to the user)

**Comment by dougludlow** [comment]
I just need to get a release out for this.
