### ISSUE TITLE
Interested in ownership...

### ISSUE THREAD

**Issue by dougludlow** [dougludlow/plugin-sass#79]
@screendriver I'd be willing to take this over.

**Comment by screendriver** [comment]
Hi @dougludlow,

thank you for your interest 👍 . I talk with my colleagues and give you feedback in the beginning next week.

**Comment by screendriver** [comment]
It went faster than expected: we would like to transfer this repository to you. Unfortunately you created a repository with the same name so I can't give you this repo: `dougludlow/plugin-sass already exists and You can only transfer a repository from an organization to yourself at this time`

**Comment by dougludlow** [comment]
@screendriver sorry, I had a fork of the repo. I've removed it now. Should be good to go. Thanks!

**Comment by dougludlow** [comment]
@screendriver I've transferred it over.

**Comment by screendriver** [comment]
Thank you very much for taking the ownership :+1:
